;; This program simulates SU(GROUP) lattice gauge fields with the
;; simple Wilson action.
;; Converted to Guile Scheme from Creutz's C++ puregauge.cc

(use-modules (ice-9 format)
             (srfi srfi-19))

(define group 2)
(define dim 4)
(define size 8)
(define hits 10)
(define beta 2.3)

(define shape #(8 8 8 8))
(define shift #(1 8 64 512))

(define nsites (* size size size size))
(define nlinks (* dim nsites))
(define vectorlength (quotient nsites 2))

;; 48-bit LCG matching drand48
(define *rng-state* 80880398)

(define (srand48 seed)
  (set! *rng-state* (logand (+ 13070 (ash seed 16)) #xFFFFFFFFFFFF)))

(define (drand48)
  (let* ((a 25214903917)
         (c 11)
         (mask #xFFFFFFFFFFFF)
         (next (logand (+ (* a *rng-state*) c) mask)))
    (set! *rng-state* next)
    (/ (exact->inexact next) 281474976710656.0)))

;; Matrix operations: 2x2 complex matrix as #(m00 m01 m10 m11)
(define id-one (vector 1.0+0.0i 0.0+0.0i 0.0+0.0i 1.0+0.0i))
(define id-zero (vector 0.0+0.0i 0.0+0.0i 0.0+0.0i 0.0+0.0i))

(define (make-id-matrix x)
  (let ((cx (make-rectangular x 0.0)))
    (vector cx 0.0+0.0i 0.0+0.0i cx)))

(define (mat-mul a b)
  (let ((a00 (vector-ref a 0)) (a01 (vector-ref a 1))
        (a10 (vector-ref a 2)) (a11 (vector-ref a 3))
        (b00 (vector-ref b 0)) (b01 (vector-ref b 1))
        (b10 (vector-ref b 2)) (b11 (vector-ref b 3)))
    (vector (+ (* a00 b00) (* a01 b10))
            (+ (* a00 b01) (* a01 b11))
            (+ (* a10 b00) (* a11 b10))
            (+ (* a10 b01) (* a11 b11)))))

(define (mat-add a b)
  (vector (+ (vector-ref a 0) (vector-ref b 0))
          (+ (vector-ref a 1) (vector-ref b 1))
          (+ (vector-ref a 2) (vector-ref b 2))
          (+ (vector-ref a 3) (vector-ref b 3))))

(define (conjugate-c z)
  (make-rectangular (real-part z) (- (imag-part z))))

(define (conjugate-mat m)
  (vector (conjugate-c (vector-ref m 0))
          (conjugate-c (vector-ref m 2))
          (conjugate-c (vector-ref m 1))
          (conjugate-c (vector-ref m 3))))

(define (project m)
  (let* ((w00 (vector-ref m 0))
         (w01 (vector-ref m 1))
         (norm (sqrt (+ (* (magnitude w00) (magnitude w00))
                        (* (magnitude w01) (magnitude w01)))))
         (inv-norm (/ 1.0 norm))
         (w00n (* w00 inv-norm))
         (w01n (* w01 inv-norm))
         (w10n (- (conjugate-c w01n)))
         (w11n (conjugate-c w00n)))
    (vector w00n w01n w10n w11n)))

(define (vtprod-elem a b)
  (let ((a00 (vector-ref a 0)) (a01 (vector-ref a 1))
        (a10 (vector-ref a 2)) (a11 (vector-ref a 3))
        (b00 (vector-ref b 0)) (b01 (vector-ref b 1))
        (b10 (vector-ref b 2)) (b11 (vector-ref b 3)))
    (real-part (+ (* a00 b00) (* a01 b10) (* a10 b01) (* a11 b11)))))

(define (vtrace-elem m)
  (real-part (+ (vector-ref m 0) (vector-ref m 3))))

;; Global simulation data
(define ulinks (make-vector nlinks id-one))
(define parity (make-vector nsites 0))
(define table1 (make-vector vectorlength id-one))
(define table2 (make-vector vectorlength id-one))
(define mtemp (vector (make-vector vectorlength id-one)
                      (make-vector vectorlength id-one)
                      (make-vector vectorlength id-one)
                      (make-vector vectorlength id-one)
                      (make-vector vectorlength id-one)))
(define sold (make-vector vectorlength 0.0))
(define snew (make-vector vectorlength 0.0))
(define accepted (make-vector vectorlength 0))
(define myindex (make-vector vectorlength 0))

(define (cleanup msg)
  (display msg) (newline)
  (exit 0))

(define (split-coords s x)
  (let loop ((i (- dim 1)) (temp s))
    (if (> i 0)
        (let* ((sh (vector-ref shift i))
               (q (quotient temp sh))
               (r (remainder temp sh)))
          (vector-set! x i q)
          (loop (- i 1) r))
        (vector-set! x 0 temp))))

(define (siteindex x)
  (+ (vector-ref x 0)
     (* 8 (vector-ref x 1))
     (* 64 (vector-ref x 2))
     (* 512 (vector-ref x 3))))

(define (vshift n dx)
  (let ((y (make-vector dim 0)))
    (split-coords n y)
    (let loop ((i 0))
      (if (< i dim)
          (begin
            (let ((d (vector-ref dx i)))
              (when (not (= d 0))
                (let ((yi (modulo (+ (vector-ref y i) d) (vector-ref shape i))))
                  (vector-set! y i (if (< yi 0) (+ yi (vector-ref shape i)) yi)))))
            (loop (+ i 1)))))
    (siteindex y)))

(define (ishift n dir dist)
  (let ((dx (make-vector dim 0)))
    (vector-set! dx dir dist)
    (vshift n dx)))

(define (makeindex n ind)
  (let ((dx (make-vector dim 0)))
    (split-coords n dx)
    (let loop ((iv 0) (site 0))
      (if (< iv vectorlength)
          (if (= (vector-ref parity site) 0)
              (begin
                (vector-set! ind iv (vshift site dx))
                (loop (+ iv 1) (+ site 1)))
              (loop iv (+ site 1)))))))

(define (vgroup g)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! g iv (project (vector-ref g iv)))))

(define (vcopy g1 g2)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! g2 iv (vector-ref g1 iv))))

(define (vprod g1 g2 g3)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! g3 iv (mat-mul (vector-ref g1 iv) (vector-ref g2 iv)))))

(define (vsum g1 g2 g3)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! g3 iv (mat-add (vector-ref g1 iv) (vector-ref g2 iv)))))

(define (vtprod g1 g2 s)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! s iv (vtprod-elem (vector-ref g1 iv) (vector-ref g2 iv)))))

(define (vtrace g s)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! s iv (vtrace-elem (vector-ref g iv)))))

(define (getlinks g lattice site link)
  (makeindex site myindex)
  (let ((sft (* nsites link)))
    (do ((iv 0 (+ iv 1)))
        ((= iv vectorlength))
      (vector-set! g iv (vector-ref lattice (+ (vector-ref myindex iv) sft))))))

(define (getconjugate g lattice site link)
  (makeindex site myindex)
  (let ((sft (* nsites link)))
    (do ((iv 0 (+ iv 1)))
        ((= iv vectorlength))
      (vector-set! g iv (conjugate-mat (vector-ref lattice (+ (vector-ref myindex iv) sft)))))))

(define (savelinks g lattice site link)
  (makeindex site myindex)
  (let ((sft (* nsites link)))
    (do ((iv 0 (+ iv 1)))
        ((= iv vectorlength))
      (vector-set! lattice (+ (vector-ref myindex iv) sft) (vector-ref g iv)))))

(define (metro old trial bias)
  (let ((expdeltas 0.0))
    (do ((iv 0 (+ iv 1)))
        ((= iv vectorlength))
      (let* ((sold-val (vector-ref sold iv))
             (snew-val (vector-ref snew iv))
             (temp (exp (* bias (- snew-val sold-val)))))
        (set! expdeltas (+ expdeltas temp))
        (vector-set! accepted iv (if (< (drand48) temp) 1 0))))
    (do ((iv 0 (+ iv 1)))
        ((= iv vectorlength))
      (when (= (vector-ref accepted iv) 1)
        (vector-set! sold iv (vector-ref snew iv))
        (vector-set! old iv (vector-ref trial iv))))
    (/ expdeltas (exact->inexact vectorlength))))

(define (ranmat g)
  (let ((idx (inexact->exact (floor (* vectorlength (drand48))))))
    (do ((iv 0 (+ iv 1)))
        ((= iv vectorlength))
      (when (>= idx vectorlength)
        (set! idx (- idx vectorlength)))
      (if (< (drand48) 0.5)
          (vector-set! g iv (vector-ref table1 idx))
          (vector-set! g iv (conjugate-mat (vector-ref table1 idx))))
      (set! idx (+ idx 1)))))

(define (vtable)
  (ranmat (vector-ref mtemp 0))
  (vprod table2 (vector-ref mtemp 0) table1)
  (vtrace table2 sold)
  (vtrace table1 snew)
  (metro table2 table1 (/ (* 6.0 beta) (exact->inexact group)))
  (vcopy table2 table1)
  (vcopy (vector-ref mtemp 0) table2)
  (vgroup table1))

(define (maketable)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (let ((b (/ beta (exact->inexact group)))
          (r1 (drand48)) (r2 (drand48)) (r3 (drand48)) (r4 (drand48))
          (r5 (drand48)) (r6 (drand48)) (r7 (drand48)) (r8 (drand48))
          (q1 (drand48)) (q2 (drand48)) (q3 (drand48)) (q4 (drand48))
          (q5 (drand48)) (q6 (drand48)) (q7 (drand48)) (q8 (drand48)))
      (let ((t1 (vector (make-rectangular (+ b (- r1 0.5)) (- r5 0.5))
                        (make-rectangular (- r2 0.5) (- r6 0.5))
                        (make-rectangular (- r3 0.5) (- r7 0.5))
                        (make-rectangular (+ b (- r4 0.5)) (- r8 0.5))))
            (t2 (vector (make-rectangular (+ b (- q1 0.5)) (- q5 0.5))
                        (make-rectangular (- q2 0.5) (- q6 0.5))
                        (make-rectangular (- q3 0.5) (- q7 0.5))
                        (make-rectangular (+ b (- q4 0.5)) (- q8 0.5)))))
        (vector-set! table1 iv t1)
        (vector-set! table2 iv t2))))
  (vgroup table1)
  (vgroup table2)
  (do ((i 0 (+ i 1)))
      ((= i 50))
    (vtable)))

(define (staple st lat site link)
  (do ((iv 0 (+ iv 1)))
      ((= iv vectorlength))
    (vector-set! st iv id-zero))
  (let ((site1 (ishift site link 1)))
    (do ((link1 0 (+ link1 1)))
        ((= link1 dim))
      (when (not (= link1 link))
        (let ((site2 (ishift site link1 1))
              (site4 (ishift site1 link1 -1))
              (site5 (ishift site link1 -1)))
          (getlinks (vector-ref mtemp 0) lat site1 link1)
          (getconjugate (vector-ref mtemp 1) lat site2 link)
          (vprod (vector-ref mtemp 0) (vector-ref mtemp 1) (vector-ref mtemp 2))
          (getconjugate (vector-ref mtemp 0) lat site link1)
          (vprod (vector-ref mtemp 2) (vector-ref mtemp 0) (vector-ref mtemp 1))
          (vsum st (vector-ref mtemp 1) st)

          (getconjugate (vector-ref mtemp 0) lat site4 link1)
          (getconjugate (vector-ref mtemp 1) lat site5 link)
          (vprod (vector-ref mtemp 0) (vector-ref mtemp 1) (vector-ref mtemp 2))
          (getlinks (vector-ref mtemp 0) lat site5 link1)
          (vprod (vector-ref mtemp 2) (vector-ref mtemp 0) (vector-ref mtemp 1))
          (vsum st (vector-ref mtemp 1) st))))))

(define (monte lattice)
  (vtable)
  (let ((stot 0.0) (eds 0.0) (iacc 0))
    (do ((color 0 (+ color 1)))
        ((= color 2))
      (do ((link 0 (+ link 1)))
          ((= link dim))
        (staple (vector-ref mtemp 4) lattice color link)
        (getlinks (vector-ref mtemp 0) lattice color link)
        (vtprod (vector-ref mtemp 0) (vector-ref mtemp 4) sold)
        (do ((hit 0 (+ hit 1)))
            ((= hit hits))
          (ranmat (vector-ref mtemp 1))
          (vprod (vector-ref mtemp 0) (vector-ref mtemp 1) (vector-ref mtemp 2))
          (vtprod (vector-ref mtemp 2) (vector-ref mtemp 4) snew)
          (set! eds (+ eds (metro (vector-ref mtemp 0) (vector-ref mtemp 2) (/ beta (exact->inexact group)))))
          (do ((iv 0 (+ iv 1)))
              ((= iv vectorlength))
            (set! iacc (+ iacc (vector-ref accepted iv)))
            (set! stot (+ stot (vector-ref sold iv)))))
        (savelinks (vector-ref mtemp 0) lattice color link)))
    (let ((stot-val (/ stot (* 2.0 (- dim 1) nlinks group hits)))
          (acc-val (/ (exact->inexact iacc) (* nlinks hits)))
          (eds-val (/ eds (* 2.0 dim hits))))
      (format #t "stot=~,6F, acc=~,6F, eds=~,6F~%" stot-val acc-val eds-val)
      stot-val)))

(define (overrelax lattice)
  (let ((stot 0.0) (eds 0.0) (iacc 0))
    (do ((color 0 (+ color 1)))
        ((= color 2))
      (do ((link 0 (+ link 1)))
          ((= link dim))
        (staple (vector-ref mtemp 4) lattice color link)
        (getlinks (vector-ref mtemp 0) lattice color link)
        (vcopy (vector-ref mtemp 4) (vector-ref mtemp 1))
        (vgroup (vector-ref mtemp 1))
        (vprod (vector-ref mtemp 0) (vector-ref mtemp 1) (vector-ref mtemp 2))
        (vprod (vector-ref mtemp 1) (vector-ref mtemp 2) (vector-ref mtemp 3))
        (do ((iv 0 (+ iv 1)))
            ((= iv vectorlength))
          (vector-set! (vector-ref mtemp 2) iv (conjugate-mat (vector-ref (vector-ref mtemp 3) iv))))
        (vtprod (vector-ref mtemp 0) (vector-ref mtemp 4) sold)
        (vtprod (vector-ref mtemp 2) (vector-ref mtemp 4) snew)
        (set! eds (+ eds (metro (vector-ref mtemp 0) (vector-ref mtemp 2) (/ beta (exact->inexact group)))))
        (do ((iv 0 (+ iv 1)))
            ((= iv vectorlength))
          (set! iacc (+ iacc (vector-ref accepted iv)))
          (set! stot (+ stot (vector-ref sold iv))))
        (savelinks (vector-ref mtemp 0) lattice color link)))
    (let ((stot-val (/ stot (* 2.0 (- dim 1) nlinks group)))
          (acc-val (/ (exact->inexact iacc) nlinks))
          (eds-val (/ eds (* 2.0 dim))))
      (format #t "stot=~,6F, acc=~,6F, eds=~,6F~%" stot-val acc-val eds-val)
      stot-val)))

(define (renorm l)
  (do ((octant 0 (+ octant 1)))
      ((= octant (* 2 dim)))
    (let ((link (* octant vectorlength)))
      (do ((iv 0 (+ iv 1)))
          ((= iv vectorlength))
        (vector-set! l (+ link iv) (project (vector-ref l (+ link iv))))))))

(define (wilson-loop u x y)
  (let ((count 0) (result 0.0))
    (do ((color 0 (+ color 1)))
        ((= color 2))
      (do ((link1 0 (+ link1 1)))
          ((= link1 dim))
        (let ((start-link2 (if (= x y) (+ link1 1) 0)))
          (do ((link2 start-link2 (+ link2 1)))
              ((= link2 dim))
            (when (not (= link1 link2))
              (set! count (+ count 1))
              (let ((corner (ishift (ishift color link1 x) link2 y)))
                (do ((iv 0 (+ iv 1)))
                    ((= iv vectorlength))
                  (vector-set! (vector-ref mtemp 0) iv id-one)
                  (vector-set! (vector-ref mtemp 1) iv id-one)
                  (vector-set! (vector-ref mtemp 2) iv id-one)
                  (vector-set! (vector-ref mtemp 3) iv id-one))
                (do ((i 0 (+ i 1)))
                    ((= i x))
                  (getlinks (vector-ref mtemp 4) u (ishift color link1 i) link1)
                  (vprod (vector-ref mtemp 0) (vector-ref mtemp 4) (vector-ref mtemp 0))
                  (getconjugate (vector-ref mtemp 4) u (ishift corner link1 (- (- 0 i) 1)) link1)
                  (vprod (vector-ref mtemp 2) (vector-ref mtemp 4) (vector-ref mtemp 2)))
                (do ((i 0 (+ i 1)))
                    ((= i y))
                  (getlinks (vector-ref mtemp 4) u (ishift corner link2 (- i y)) link2)
                  (vprod (vector-ref mtemp 1) (vector-ref mtemp 4) (vector-ref mtemp 1))
                  (getconjugate (vector-ref mtemp 4) u (ishift color link2 (- (- y i) 1)) link2)
                  (vprod (vector-ref mtemp 3) (vector-ref mtemp 4) (vector-ref mtemp 3)))
                (vprod (vector-ref mtemp 0) (vector-ref mtemp 1) (vector-ref mtemp 0))
                (vprod (vector-ref mtemp 0) (vector-ref mtemp 2) (vector-ref mtemp 0))
                (vtprod (vector-ref mtemp 0) (vector-ref mtemp 3) sold)
                (do ((iv 0 (+ iv 1)))
                    ((= iv vectorlength))
                  (set! result (+ result (vector-ref sold iv))))))))))
    (let ((res (/ result (* group vectorlength count))))
      (format #t " ~A by ~A loop = ~,6F~%" x y res)
      res)))

(define (init)
  (srand48 1234)
  (do ((iv 0 (+ iv 1)))
      ((= iv nsites))
    (let ((x (make-vector dim 0)))
      (split-coords iv x)
      (let ((p 0))
        (do ((i 0 (+ i 1)))
            ((= i dim))
          (set! p (logxor p (vector-ref x i))))
        (vector-set! parity iv (logand p 1)))))
  (maketable)
  (display "initialization done") (newline))

(define (main args)
  (when (> (length args) 1)
    (set! beta (string->number (cadr args))))
  (init)
  (format #t "lattice size ~A by ~A by ~A by ~A~%" size size size size)
  (format #t " vectorlength = ~A~%" vectorlength)
  (format #t "group=SU(~A)   beta = ~,4F~%" group beta)
  (format #t "-----------------~%")

  (display "test monte") (newline)
  (do ((iter 0 (+ iter 1)))
      ((= iter 5))
    (let ((t0 (get-internal-run-time))
          (count 0))
      (do ((i 0 (+ i 1)))
          ((= i 5))
        (monte ulinks)
        (set! count (+ count 1)))
      (renorm ulinks)
      (let* ((t1 (get-internal-run-time))
             (elapsed (/ (exact->inexact (- t1 t0)) internal-time-units-per-second))
             (microsec (* (/ 1000000.0 (* count nlinks)) elapsed)))
        (format #t "running at ~G microseconds per link~%" microsec)
        (wilson-loop ulinks 2 2))))

  (display "test overrelax") (newline)
  (do ((iter 0 (+ iter 1)))
      ((= iter 5))
    (let ((t0 (get-internal-run-time))
          (count 0))
      (do ((i 0 (+ i 1)))
          ((= i 5))
        (overrelax ulinks)
        (set! count (+ count 1)))
      (renorm ulinks)
      (let* ((t1 (get-internal-run-time))
             (elapsed (/ (exact->inexact (- t1 t0)) internal-time-units-per-second))
             (microsec (* (/ 1000000.0 (* count nlinks)) elapsed)))
        (format #t "running at ~G microseconds per link~%" microsec))))
  (cleanup "all done"))

(main (command-line))
